
version: "3"

services:
  app:
    container_name: user-management-api
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "5050:5050"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/user_management_db" 

  mongo:
    container_name: mongo
    image: mongo:latest
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
